name: GitHub Classroom Workflow

on: 
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Make test script executable
      run: chmod +x run_tests.sh
      
    - name: Run custom test suite (for detailed feedback)
      run: ./run_tests.sh
      continue-on-error: true
      
    - name: Autograding
      uses: education/autograding@v1
      id: autograder
      continue-on-error: true
      
    - name: Generate feedback report
      run: |
        echo "## Autograding Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Test Execution Summary" >> $GITHUB_STEP_SUMMARY
        echo "The autograder has completed running all tests." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Detailed Test Results" >> $GITHUB_STEP_SUMMARY
        echo "Check the 'Run custom test suite' step above for detailed test output." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Physics Validation" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Basic calculations (F = ma)" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Decimal precision handling" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Edge cases (zero values)" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Negative acceleration scenarios" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Input/output format verification" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Grading Breakdown" >> $GITHUB_STEP_SUMMARY
        echo "- **Compilation (15 pts)**: Code compiles without errors" >> $GITHUB_STEP_SUMMARY
        echo "- **Basic Calculations (40 pts)**: Correct F=ma implementation" >> $GITHUB_STEP_SUMMARY
        echo "- **Edge Cases (30 pts)**: Handles zero and negative values" >> $GITHUB_STEP_SUMMARY
        echo "- **Format & Prompts (10 pts)**: Correct user interface" >> $GITHUB_STEP_SUMMARY
        echo "- **Comprehensive Testing (5 pts)**: All tests pass" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Total: 100 points**" >> $GITHUB_STEP_SUMMARY
